### ISSUE TITLE
Incorrect assignment to Bioconductor

### ISSUE THREAD

**Issue by llrs** [r-lib/sessioninfo#24]
I have a package that I install locally, via `install.packages(".", repos = NULL)`, but it depends on Bioconductor packages. In order to be able to test it correctly with continous integration tools I have inserted the biocViews. It is not published on Bioconductor. I expected to see it installed from local, however it was as Bioconductor.

Could this be improved by checking if biocViews is empty or not (not only if it is present or not)? 

I think this might happen to other packages that are currently on CRAN (But I couldn't find examples them now).

**Comment by gaborcsardi** [comment]
Sounds good, do you want to submit a PR?

**Comment by gaborcsardi** [comment]
Closed by #25.
