### ISSUE TITLE
Saving session_info output to file

### ISSUE THREAD

**Issue by briatte** [r-lib/sessioninfo#30]
(The following use case is classroom-based.)

I like to include a `session_info.txt` file in my repos: it's the easiest way for users to understand the package dependencies.

My code to create the file:

```r
sink("session_info.txt", append = FALSE)
# print() needed to work when used with 'Source on Save' in RStudio
# without it, sink() will save an empty file
print(sessioninfo::session_info())
sink()
```

When I share the repo with someone, I also share [a script](https://gist.github.com/briatte/14e47fb0cfb8801f25c889edea3fcd9b) that parses the file in order to find which packages need to be installed or updated.

Is there a better way to save sessioninfo's output to a plain text file?

**Comment by gaborcsardi** [comment]
I don't think that there is a better way currently, but we should probably have a good way that works well with the pkg package.

**Comment by briatte** [comment]
I think that'd be great.

In my view, a plain text file produced by `sessioninfo` is the best way to share what's installed and loaded. It is unobtrusive and lightweight (_contra_ full-reproducibility solutions like e.g. `packrat`).
