### ISSUE TITLE
Sessioninfo in reprex, consider reordering columns?

### ISSUE THREAD

**Issue by jimhester** [r-lib/sessioninfo#31]
Unfortunately with the way it prints now with width 80 the source column is wrapped to the end, which makes it basically impossible to align with the package name, to see if a package is from GH or CRAN. e.g. the session info in https://github.com/jimhester/itdepends/issues/8

Could we do something to make this case better? Either here or possibly in reprex by changing the default width when rendering the session info? (cc @jennybc)

**Comment by jennybc** [comment]
Yeah this bugs me regularly. `lib` is the column least important in a reprex, I think. It would be great to find a more compact representation that fits on one line by design.

**Comment by gaborcsardi** [comment]
As @kevinushey mentioned a long time ago at https://github.com/tidyverse/reprex/issues/225#issue-384553474 we should just avoid wrapping the output. It is pretty hard to wrap a table otherwise.
