### ISSUE TITLE
Time zone is not used for dates in output table

### ISSUE THREAD

**Issue by wch** [r-lib/sessioninfo#32]
For example:

```
─ Session info ───────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       macOS High Sierra 10.13.6   
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Chicago             
 date     2019-02-14                  

─ Packages ───────────────────────────────────────────────────────────────────────────
 ! package     * version    date       lib source                         
...
   httpuv        1.4.5.9004 2019-02-15 [1] local                          
...
```

The current date at the top is 02-14, but the date listed for the package is 02-15.

I'm guessing this is because the date for the package is 02-15 in UTC:

```
> packageDescription('httpuv')
Package: httpuv
Type: Package
Title: HTTP and WebSocket Server Library
Version: 1.4.5.9004
....
Built: R 3.5.1; x86_64-apple-darwin15.6.0; 2019-02-15 02:49:39 UTC; unix

-- File: /Users/winston/R/3.5/httpuv/Meta/package.rds 
```

This is the kind of bug that a developer who lives in GMT will never see... ;)

**Comment by gaborcsardi** [comment]
Hmmm, isn't it better to show the dates in UTC? Otherwise people might get different output for the same exact package versions.

**Comment by wch** [comment]
That is a valid point... But it is still confusing that the date can appear to be in the future, since it's non-obvious that the package date is UTC, while the current date (above) is local. Maybe if the column was named `date_utc`? But I suppose that feels kind of verbose. I don't know if it's really better than the status quo.

**Comment by gaborcsardi** [comment]
The column name is a good idea. I will not change it in the data frame, but I'll change it in the print method.

**Comment by gaborcsardi** [comment]
Looks like this now, hopefully this is better:
```
❯ package_info()
 package     * version    date (UTC) lib source
 cachem        1.0.6      2021-08-19 [1] standard (@1.0.6)
 callr         3.7.0      2021-04-20 [1] standard (@3.7.0)
 cli           3.0.1      2021-07-17 [1] standard (@3.0.1)
```
