### ISSUE TITLE
Sys.timezone is not always a string

### ISSUE THREAD

**Issue by QuLogic** [r-lib/sessioninfo#34]
Tests assert that [`platform_info()$tz` is a string](https://github.com/r-lib/sessioninfo/blob/master/tests/testthat/test-platform-info.R#L17). This is obtained [directly from `Sys.timezone`](https://github.com/r-lib/sessioninfo/blob/master/R/platform-info.R#L34) without any other processing.

However, the [result of `Sys.timezone`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/timezones.html) can be a string _or_ `NA`. The test fails to handle the latter case, or the code fails to normalize it (not sure which is intended.)

**Comment by gaborcsardi** [comment]
Thansk! You are right, it should be `is_string(pi$tz) || identical(pi$tz, NA_character_)` or maybe just `is.character(pi$tz) && length(pi$tz) == 1`. Do you want to submit a PR?
