### ISSUE TITLE
Include Matrix products

### ISSUE THREAD

**Issue by llrs** [r-lib/sessioninfo#37]
I am not sure if this is one of the focus of the package. But I am comparing two machines and I noted that session_info doesn't return any information about the Matrix products (BLAS/LAPACK) libraries used by the session.

The documentation I found relevant for such reporting would be `extSoftVersion()` and the functions mentioned there. I could put something together in a new function and make a PR.

**Comment by gaborcsardi** [comment]
> I could put something together in a new function and make a PR.

Yes, please! Thank you!

**Comment by llrs** [comment]
Closing, the PR was merged
