### ISSUE TITLE
adding `attached` parameter to session_info() and package_info()

### ISSUE THREAD

**Issue by engineerchange** [r-lib/sessioninfo#42]
Thank you for creating and maintaining such a useful package!

I think there is some use case to return the session_info() and package_info() for the attached packages only. Example here: https://www.tidymodels.org/learn/work/bayes-opt/

A parameter that allows for this would save some trimming on the user's side.

**Comment by gaborcsardi** [comment]
You can filter the data frame that is returned, it has an `attached` column:

```r
❯ pi <- sessioninfo::package_info()
❯ subset(pi, attached)
 package * version    date       lib source
 cli     * 2.2.0.9000 2021-01-21 [1] local
 crayon  * 1.3.4.9000 2020-12-29 [1] local

[1] /Users/gaborcsardi/Library/R/4.0/library
[2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

If you want the complete session info, `session_info()` returns a list of `platform` and `packages`, and you can filter `packages` the same way.

**Comment by engineerchange** [comment]
Thank you for getting back so quickly! I did look through the code yesterday, and I saw that packages was returned as a data.frame.

I guess the utility I see is being able to do:

```
> sessioninfo::session_info(attached=TRUE)
```
versus
```
> sessioninfo::platform_info()
> pi <- sessioninfo::package_info()
> subset(pi,attached)
```

The former is more elegant, and much easier to debug remotely what others got going on in their session with a single command versus three; it also has the output in a more compact form.

---

I took a stab at a PR, but apparently it's a bit more than just editing as:
`package-info.R`
```
package_info <- function(pkgs = NULL, include_base = FALSE, attached = FALSE,
                         dependencies = NA)
```
and
```
  if (attached) pkgs <- pkgs[pkgs$attached, ]
  ```
and additionally,
`session-info.R`
```
packages = package_info(pkgs, include_base = include_base, attached = attached)
```

The way dependencies are handled was a bit confusing for me, as I couldn't get the above to work locally, as expected.

**Comment by gaborcsardi** [comment]
I am reluctant to add this, because it does not seem like a feature that is often needed (in fact, I don't really understand why you would want an incomplete session info in the first place), and because it (obviously) complicates the code base.

**Comment by gaborcsardi** [comment]
OK, I'll think about this, maybe we could make the `pkgs` argument magical. FWIW to determine the attached packages, one needs to parse `search()`.

**Comment by gaborcsardi** [comment]
You can now write 
```r
session_info("!attached")
```
to list the attached packages only.
