### ISSUE TITLE
Remove emojis option for session_info() ?

### ISSUE THREAD

**Issue by davidbudzynski** [r-lib/sessioninfo#57]
Hi! Is there a way to remove emojis from the `session_info()` or any plans at to add this feature in? I'm on Archlinux and I can't see them in the latest version of Rstudio even though I have emoji fonts. I'd like to use this package at work I don't understand what would be the purpose for them or their transcriptions in the line below and my colleagues would probably be confused when in comes to this. 
 
![image](https://user-images.githubusercontent.com/56514985/142063123-86330d21-335f-4d10-b453-99a669ea33e3.png)

**Comment by gaborcsardi** [comment]
>  I don't understand what would be the purpose for them or their transcriptions in the line below

The purpose is that it makes it easy to tell if two session infos are different.

**Comment by davidbudzynski** [comment]
that's an interesting choice to use emojis for that. I guess this cannot be disabled?

**Comment by gaborcsardi** [comment]
It is much easier to compare three emojis than `127a2ec00989b9f7faf671ed470be7f8` and `ddf100612805359cd81fdc5ce3b9fbba`. 

You can "disable" it like this:
```
sessioninfo::session_info()[1:2]
```
