### ISSUE TITLE
Sorting of Dependencies

### ISSUE THREAD

**Issue by muschellij2** [r-lib/sessioninfo#65]
In some instances, it may be useful to have the result given back in the non-sorted manner (as you can infer the level of dependencies from the order of the list) and a switch off for https://github.com/r-lib/sessioninfo/blob/ecb294103635a4e4c3fb54581654ca060eb1c75a/R/dependent-packages.R#L28

**Comment by gaborcsardi** [comment]
You can't infer the dependencies from the order, though, so I am reluctant to add this. If you want the dependencies then I would rather add another column that explicitly lists them.

Or use `pak::pkg_deps_tree()` to print the whole dependency tree, or `pkg_deps_explain()` to see why a package is needed for another one:
```
❯ pak::pkg_deps_explain("tibble", "rlang")
tibble -> ellipsis -> rlang
tibble -> lifecycle -> rlang
tibble -> pillar -> ellipsis -> rlang
tibble -> pillar -> lifecycle -> rlang
tibble -> pillar -> rlang
tibble -> pillar -> vctrs -> ellipsis -> rlang
tibble -> pillar -> vctrs -> rlang
tibble -> rlang
tibble -> vctrs -> ellipsis -> rlang
tibble -> vctrs -> rlang
```
