### ISSUE TITLE
Avoid inheriting explicitly from "list"

### ISSUE THREAD

**Issue by krlmlr** [r-lib/sessioninfo#67]
`session_info()` should not be treated as a vector:

``` r
vctrs::vec_is(sessioninfo::session_info())
#> [1] TRUE
vctrs::vec_size(sessioninfo::session_info())
#> [1] 2
```

<sup>Created on 2021-12-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gaborcsardi** [comment]
Why not? If it is not a `list` then some things do not work, e.g. `jsonlite::toJSON()`.

**Comment by krlmlr** [comment]
Good point. Maybe @lionel- or @DavisVaughan can weigh in?

**Comment by gaborcsardi** [comment]
Or we can just leave it as is, until there is a problem with it?

**Comment by krlmlr** [comment]
🍿

**Comment by lionel-** [comment]
@krlmlr I don't have an opinion on whether it should be a list, a data frame, or a scalar. It seems like this depends on the typical usage made of the data structure and this sort of things is up to the maintainer.
