### ISSUE TITLE
parsing sessioinfo object from GH actions?

### ISSUE THREAD

**Issue by njtierney** [r-lib/sessioninfo#70]
Hello!

I'm currently trying to identify system differences between my local machine and github actions, and I was wondering if there might be a way to extract session info from GH actions?

https://github.com/greta-dev/greta/runs/5296503551?check_suite_focus=true#step:10:15

the `sessioninfo::session_diff()` function looks perfect, and I love how https://github.com/r-lib/sessioninfo#comparing-session-information shows comparison with an issue link.

Ideally, it would be great if I could get back the sessioninfo object from GH actions somehow, so that I can do a join on package names to work out if and where there are different package versions - that is the end goal that I am looking for here.

**Comment by gaborcsardi** [comment]
Parsing is hard, but since https://github.com/r-lib/sessioninfo/pull/68 there is direct support for diffing, and this will also improve the diffs: https://github.com/r-lib/sessioninfo/pull/69

So this is very much in motion, I would say, and I am going to close this issue.

**Comment by njtierney** [comment]
Oh wow, that is amazing! Exactly what I'm after!
