### ISSUE TITLE
sessionInfo reports incorrect operating system

### ISSUE THREAD

**Issue by ThomasBaardemans** [r-lib/sessioninfo#76]
When I run sessionInfo it reports my OS as windows 10:
![afbeelding](https://user-images.githubusercontent.com/49636966/174275821-103f688b-26ae-4278-bcf5-99e952aed934.png)

But I have windows 11:
![afbeelding](https://user-images.githubusercontent.com/49636966/174276023-f3e8c5d3-a272-4270-9db8-60b263e2c969.png)

**Comment by gaborcsardi** [comment]
This is from `sessionInfo()`, which is a base R function and not from this package, so please report a bug to base R if you would like to pursue this.
