### ISSUE TITLE
Capture base URLs of repos 

### ISSUE THREAD

**Issue by parmsam-pfizer** [r-lib/sessioninfo#81]
It doesn't appear that the base URL(s) of the repositories to use (by `install.packages()` or `update.packages()`) are captured in {sessioninfo}. It would be nice to have this in the session info section.

Here's a simple utility function to return a list with that info:
``` 
get_repo_urls <- function() {
  as.list(getOption("repos"))
}
```

**Comment by gaborcsardi** [comment]
Thanks for the suggestion! URLs may contain sensitive information, so I am afraid that we are not going to do this at this point.
